### ISSUE TITLE
docker-compose not working , redirect to wrong domain

### ISSUE THREAD

**Issue by changchichung** [bubbajames-docker/sendy#15]
my docker-compose.yml
```
version: "3.7"

# Volumes for persisted data.
volumes:
  data_sendy:
    labels:
      co.sendy.description: "Data volume for Sendy Database."

# Secret files so they're not exposed via 'docker inspect'
secrets:
  db_password:
    file: secrets/db_password
  db_root_password:
    file: secrets/db_root_password

services:
  # Database: MySQL
  db_sendy:
    hostname: db_sendy
    container_name: db_sendy
    image: mysql:5.6
    env_file:
      - sendy.env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - data_sendy:/var/lib/mysql

  # WebApp: Apache2+PHP+Sendy
  sendy:
    hostname: sendy
    container_name: sendy
    depends_on:
      - db_sendy
    image: sendy:latest
    build:
      context: .
      # Uncomment to enabled XDEBUG build
      # target: debug
    env_file:
      - sendy.env
    secrets:
      - db_password
    ports:
      - 8080:80

  # Load Balancer: HAProxy
  load-balancer:
    hostname: lb_sendy
    container_name: lb_sendy
    image: lb_sendy
    build:
      context: .
      dockerfile: haproxy/Dockerfile
    env_file:
      - sendy.env
    ports:
      - 804:80
      - 4434:443
```
.env file
```
SENDY_PROTOCOL=https
# Update FQDN to match your Sendy licensed domain.
SENDY_FQDN=sendy.abc.com
MYSQL_HOST=db_sendy
MYSQL_DATABASE=sendy
MYSQL_USER=sendy
MYSQL_PASSWORD_FILE=/run/secrets/db_password
#MYSQL_PASSWORD=db_password

# XDEBUG
# REQUIRES BUILDING image with XDEBUG installed.
# See Dockerfile header for details.

# Uncomment to set XDEBUG enviorment configuration. Ensure `remote_port` does not have conflicts.
#XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1
```
when I try to open the url , it redirect to https://campaigns.example.com/_install.php
no matter what I configure in .env file
any suggestion to fix ?
